### ISSUE TITLE
Panic on 386 system

### ISSUE THREAD

**Issue by xinaxu** [filecoin-project/go-fil-commp-hashhash#19]
The utility is panicing on 386 system, blocking CI workflow for repo that depends on this package.

```bash
$ GOARCH=386 go install github.com/filecoin-project/go-fil-commp-hashhash/cmd/stream-commp@latest
$ truncate -s 1G ./test.img
$ cat test.img | ~/go/bin/linux_386/stream-commp -d

panic: runtime error: slice bounds out of range [:-2147483616]

goroutine 145 [running]:
github.com/filecoin-project/go-fil-commp-hashhash.(*Calc).hashSlab254(0x9912000, 0x1a, {0x9dac000, 0x20, 0x40})
        /home/shane/go/pkg/mod/github.com/filecoin-project/go-fil-commp-hashhash@v0.2.0/commp.go:351 +0x1c3
github.com/filecoin-project/go-fil-commp-hashhash.(*Calc).addLayer.func1()
        /home/shane/go/pkg/mod/github.com/filecoin-project/go-fil-commp-hashhash@v0.2.0/commp.go:320 +0x25c
created by github.com/filecoin-project/go-fil-commp-hashhash.(*Calc).addLayer
        /home/shane/go/pkg/mod/github.com/filecoin-project/go-fil-commp-hashhash@v0.2.0/commp.go:289 +0xce
```

**Comment by ribasushi** [comment]
@xinaxu sorry took a while to get to this.
Ther specific line/fix is this: https://github.com/filecoin-project/go-fil-commp-hashhash/pull/20/commits/86d57f8d8427ffb7b29869b7f407dc5ccd287a49#diff-ff08497303a4fc3871e30371d803316a416c976776c05c0c19a8ea171484e86cL316-R316

**Comment by ribasushi** [comment]
@xinaxu :shipit:
